version: '3'

volumes:
  database_local:

services:
  yzp_blog:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: blog_image_local
    container_name: blog_container_local
    working_dir: /django_app
    volumes:
      - database_local:/django_app/database
      - .:/django_app
    ports:
      - "8000:8000"
    command: /start.sh
