version: '3'

volumes:
  static:
  database:

services:
  yzp_blog:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: blog_image_production
    container_name: blog_container_production
    working_dir: /django_app
    volumes:
      - database:/django_app/database
      - static:/django_app/static
    env_file:
      - .envs/.production
    ports:
      - "8000:8000"
    command: /start.sh

  yzp_blog_nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: nginx_image
    container_name: nginx_container
    volumes:
      - static:/apps/yzp_blog/static
    ports:
      - "80:80"
      - "443:443"
