# Generated by Django 3.0.3 on 2020-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200208_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='title',
            field=models.CharField(blank=True, max_length=10, verbose_name='标题'),
        ),
    ]
